service: trainingproject
app: my-express-app
org: pragadeesh

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: '*'

custom:
  tableName: users

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getUser:
    handler: src/apis/user.getUser
    events:
      - http:
          path: user/{ID}
          method: GET
          cors: true
  getAllUsers:
    handler: src/apis/user.getAllUsers
    events:
      - http:
          path: all-users/
          method: GET
          cors: true
  createUser:
    handler: src/apis/user.createUser
    events:
      - http:
          path: user/
          method: POST
          cors: true
  editUser:
    handler: src/apis/user.editUser
    events:
      - http:
          path: user/
          method: PUT
          cors: true
  deleteUser:
    handler: src/apis/user.deleteUser
    events:
      - http:
          path: user/{ID}
          method: DELETE
          cors: true
        
resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST